// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
)

type ItslogEtl struct {
	ID       int64
	Inserted int64
	LastRun  sql.NullInt64
	KeyID    string
	Name     string
	Kind     string
	Body     sql.NullString
}

type ItslogEvent struct {
	ID        int64
	Timestamp int64
	KeyID     string
	Cluster   sql.NullString
	Tags      string
	Value     sql.NullString
}

type ItslogSummary struct {
	ID          int64
	LastUpdated int64
	Date        string
	KeyID       string
	Operation   string
	Tags        string
	Value       string
	Count       float64
	Hash        sql.NullString
}
