// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package models

import (
	"context"
	"database/sql"
	"time"
)

const getAllSummaries = `-- name: GetAllSummaries :many
SELECT id, last_run, date, key_id, operation, tags, value, count FROM itslog_summary
`

// ------------------------------------------------------
// SUMMARY
// ------------------------------------------------------
func (q *Queries) GetAllSummaries(ctx context.Context) ([]ItslogSummary, error) {
	rows, err := q.db.QueryContext(ctx, getAllSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItslogSummary
	for rows.Next() {
		var i ItslogSummary
		if err := rows.Scan(
			&i.ID,
			&i.LastRun,
			&i.Date,
			&i.KeyID,
			&i.Operation,
			&i.Tags,
			&i.Value,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctTags = `-- name: GetDistinctTags :many
SELECT DISTINCT tags
FROM itslog_events
`

func (q *Queries) GetDistinctTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tags string
		if err := rows.Scan(&tags); err != nil {
			return nil, err
		}
		items = append(items, tags)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getETL = `-- name: GetETL :one
SELECT name, kind, body, last_run
FROM itslog_etl
WHERE
  name = ?
LIMIT 1
`

type GetETLRow struct {
	Name    string
	Kind    string
	Body    sql.NullString
	LastRun sql.NullTime
}

func (q *Queries) GetETL(ctx context.Context, name string) (GetETLRow, error) {
	row := q.db.QueryRowContext(ctx, getETL, name)
	var i GetETLRow
	err := row.Scan(
		&i.Name,
		&i.Kind,
		&i.Body,
		&i.LastRun,
	)
	return i, err
}

const insertETL = `-- name: InsertETL :exec
;



INSERT OR REPLACE INTO itslog_etl (
  key_id, name, kind, body
) VALUES (
  ?, ?, ?, ?
)
`

type InsertETLParams struct {
	KeyID string
	Name  string
	Kind  string
	Body  sql.NullString
}

// ------------------------------------------------------
// ETL
// ------------------------------------------------------
func (q *Queries) InsertETL(ctx context.Context, arg InsertETLParams) error {
	_, err := q.db.ExecContext(ctx, insertETL,
		arg.KeyID,
		arg.Name,
		arg.Kind,
		arg.Body,
	)
	return err
}

const insertFullSummary = `-- name: InsertFullSummary :exec
INSERT OR REPLACE INTO itslog_summary (
  last_run, key_id, date, operation, tags, value, count
  ) VALUES (
  ?, ?, ?, ?, ?, ?, ?
  )
`

type InsertFullSummaryParams struct {
	LastRun   time.Time
	KeyID     string
	Date      string
	Operation string
	Tags      string
	Value     string
	Count     float64
}

func (q *Queries) InsertFullSummary(ctx context.Context, arg InsertFullSummaryParams) error {
	_, err := q.db.ExecContext(ctx, insertFullSummary,
		arg.LastRun,
		arg.KeyID,
		arg.Date,
		arg.Operation,
		arg.Tags,
		arg.Value,
		arg.Count,
	)
	return err
}

const insertSummary = `-- name: InsertSummary :exec
INSERT OR REPLACE INTO itslog_summary (
  key_id, date, operation, tags, value, count
  ) VALUES (
  ?, ?, ?, ?, ?, ?
  )
`

type InsertSummaryParams struct {
	KeyID     string
	Date      string
	Operation string
	Tags      string
	Value     string
	Count     float64
}

func (q *Queries) InsertSummary(ctx context.Context, arg InsertSummaryParams) error {
	_, err := q.db.ExecContext(ctx, insertSummary,
		arg.KeyID,
		arg.Date,
		arg.Operation,
		arg.Tags,
		arg.Value,
		arg.Count,
	)
	return err
}

const logEvent = `-- name: LogEvent :one

INSERT INTO itslog_events (
  timestamp, key_id, cluster, tags, value
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id
`

type LogEventParams struct {
	Timestamp string
	KeyID     string
	Cluster   sql.NullString
	Tags      string
	Value     sql.NullString
}

// https://docs.sqlc.dev/en/latest/tutorials/getting-started-sqlite.html
// ------------------------------------------------------
// LOGGING
// ------------------------------------------------------
func (q *Queries) LogEvent(ctx context.Context, arg LogEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, logEvent,
		arg.Timestamp,
		arg.KeyID,
		arg.Cluster,
		arg.Tags,
		arg.Value,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const readSummaries = `-- name: ReadSummaries :many
;

SELECT 
  date, 
  operation, 
  COALESCE(tags, '') as tags, 
  value,
  count
FROM itslog_summary
WHERE 
  tags LIKE COALESCE(?, '%')
  AND
  operation LIKE ?
ORDER BY id
`

type ReadSummariesParams struct {
	Tags      string
	Operation string
}

type ReadSummariesRow struct {
	Date      string
	Operation string
	Tags      string
	Value     string
	Count     float64
}

func (q *Queries) ReadSummaries(ctx context.Context, arg ReadSummariesParams) ([]ReadSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, readSummaries, arg.Tags, arg.Operation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadSummariesRow
	for rows.Next() {
		var i ReadSummariesRow
		if err := rows.Scan(
			&i.Date,
			&i.Operation,
			&i.Tags,
			&i.Value,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readSummary = `-- name: ReadSummary :one
SELECT 
  date, 
  operation, 
  tags, 
  value,
  count
FROM itslog_summary
WHERE 
  tags LIKE ?
  AND
  operation LIKE ?
ORDER BY id
LIMIT 1
`

type ReadSummaryParams struct {
	Tags      string
	Operation string
}

type ReadSummaryRow struct {
	Date      string
	Operation string
	Tags      string
	Value     string
	Count     float64
}

func (q *Queries) ReadSummary(ctx context.Context, arg ReadSummaryParams) (ReadSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, readSummary, arg.Tags, arg.Operation)
	var i ReadSummaryRow
	err := row.Scan(
		&i.Date,
		&i.Operation,
		&i.Tags,
		&i.Value,
		&i.Count,
	)
	return i, err
}

const updateLastRun = `-- name: UpdateLastRun :exec
UPDATE itslog_etl
  SET 
    last_run = CURRENT_TIMESTAMP 
WHERE 
  name = ?
`

func (q *Queries) UpdateLastRun(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, updateLastRun, name)
	return err
}
