// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"time"
)

type ItslogDictionary struct {
	ID         int64
	Timestamp  time.Time
	SourceName string
	EventName  string
	SourceHash int64
	EventHash  int64
}

type ItslogEvent struct {
	ID        int64
	Timestamp time.Time
	Source    int64
	Event     int64
}

type ItslogSummary struct {
	ID        int64
	Operation string
	Source    string
	Event     sql.NullString
	Value     float64
}
