// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"time"
)

type ItslogDictionary struct {
	ID         int64
	Timestamp  time.Time
	SourceName string
	EventName  string
	SourceHash int64
	EventHash  int64
}

type ItslogEvent struct {
	ID         int64
	Timestamp  time.Time
	SourceHash int64
	EventHash  int64
}

type ItslogMetadatum struct {
	ID    int64
	Key   string
	Value string
}

type ItslogSummary struct {
	ID         int64
	Timestamp  time.Time
	Operation  string
	SourceName string
	EventName  sql.NullString
	Value      float64
}
