// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
)

type Itslog struct {
	ID        int64
	Timestamp sql.NullTime
	Event     string
	Value     string
	Type      string
}
