// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package models

import (
	"context"
)

const logIt = `-- name: LogIt :one

INSERT INTO itslog (
  event, value, type
) VALUES (
  ?, ?, ?
)
RETURNING id
`

type LogItParams struct {
	Event string
	Value string
	Type  int64
}

// https://docs.sqlc.dev/en/latest/tutorials/getting-started-sqlite.html
func (q *Queries) LogIt(ctx context.Context, arg LogItParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, logIt, arg.Event, arg.Value, arg.Type)
	var id int64
	err := row.Scan(&id)
	return id, err
}
