// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package models

import (
	"context"
)

const logEvent = `-- name: LogEvent :one

INSERT INTO events (
  source, event
) VALUES (
  ?, ?
)
RETURNING id
`

type LogEventParams struct {
	Source int64
	Event  int64
}

// https://docs.sqlc.dev/en/latest/tutorials/getting-started-sqlite.html
func (q *Queries) LogEvent(ctx context.Context, arg LogEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, logEvent, arg.Source, arg.Event)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateDictionary = `-- name: UpdateDictionary :exec
INSERT OR IGNORE INTO dictionary (
  event_source, event_name, source_hash, event_hash
) VALUES (
  ?, ?, ?, ?
)
`

type UpdateDictionaryParams struct {
	EventSource string
	EventName   string
	SourceHash  int64
	EventHash   int64
}

func (q *Queries) UpdateDictionary(ctx context.Context, arg UpdateDictionaryParams) error {
	_, err := q.db.ExecContext(ctx, updateDictionary,
		arg.EventSource,
		arg.EventName,
		arg.SourceHash,
		arg.EventHash,
	)
	return err
}
