// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"time"
)

type ItslogEtl struct {
	ID       int64
	Inserted time.Time
	KeyID    int64
	Name     string
	LastRun  sql.NullTime
	Sql      string
}

type ItslogEvent struct {
	ID          int64
	Timestamp   time.Time
	KeyID       int64
	ClusterHash sql.NullInt64
	TagsHash    int64
	ValueHash   sql.NullInt64
}

type ItslogLookup struct {
	ID        int64
	Timestamp time.Time
	KeyID     int64
	Hash      int64
	Name      string
}

type ItslogSummary struct {
	ID         int64
	Date       string
	KeyID      int64
	Operation  string
	SourceName sql.NullString
	EventName  sql.NullString
	Value      float64
}
