// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package models

import (
	"context"
	"database/sql"
	"time"
)

const getAllSummaries = `-- name: GetAllSummaries :many
SELECT id, date, key_id, operation, source_name, event_name, value FROM itslog_summary
`

// ------------------------------------------------------
// SUMMARY
// ------------------------------------------------------
func (q *Queries) GetAllSummaries(ctx context.Context) ([]ItslogSummary, error) {
	rows, err := q.db.QueryContext(ctx, getAllSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItslogSummary
	for rows.Next() {
		var i ItslogSummary
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.KeyID,
			&i.Operation,
			&i.SourceName,
			&i.EventName,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getETL = `-- name: GetETL :one
SELECT sql, last_run
FROM itslog_etl
WHERE
  name = ?
LIMIT 1
`

type GetETLRow struct {
	Sql     string
	LastRun sql.NullTime
}

func (q *Queries) GetETL(ctx context.Context, name string) (GetETLRow, error) {
	row := q.db.QueryRowContext(ctx, getETL, name)
	var i GetETLRow
	err := row.Scan(&i.Sql, &i.LastRun)
	return i, err
}

const insertETL = `-- name: InsertETL :exec
;


INSERT OR REPLACE INTO itslog_etl (
  key_id, name, sql
) VALUES (
  ?, ?, ?
)
`

type InsertETLParams struct {
	KeyID int64
	Name  string
	Sql   string
}

// ------------------------------------------------------
// ETL
// ------------------------------------------------------
func (q *Queries) InsertETL(ctx context.Context, arg InsertETLParams) error {
	_, err := q.db.ExecContext(ctx, insertETL, arg.KeyID, arg.Name, arg.Sql)
	return err
}

const insertSummary = `-- name: InsertSummary :exec
INSERT OR REPLACE INTO itslog_summary (
  date, operation, source_name, event_name, value
  ) VALUES (
  ?, ?, ?, ?, ?
  )
`

type InsertSummaryParams struct {
	Date       string
	Operation  string
	SourceName sql.NullString
	EventName  sql.NullString
	Value      float64
}

func (q *Queries) InsertSummary(ctx context.Context, arg InsertSummaryParams) error {
	_, err := q.db.ExecContext(ctx, insertSummary,
		arg.Date,
		arg.Operation,
		arg.SourceName,
		arg.EventName,
		arg.Value,
	)
	return err
}

const logEvent = `-- name: LogEvent :one

INSERT INTO itslog_events (
  timestamp, key_id, cluster, tags, value
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id
`

type LogEventParams struct {
	Timestamp time.Time
	KeyID     string
	Cluster   sql.NullString
	Tags      string
	Value     sql.NullString
}

// https://docs.sqlc.dev/en/latest/tutorials/getting-started-sqlite.html
// ------------------------------------------------------
// LOGGING
// ------------------------------------------------------
func (q *Queries) LogEvent(ctx context.Context, arg LogEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, logEvent,
		arg.Timestamp,
		arg.KeyID,
		arg.Cluster,
		arg.Tags,
		arg.Value,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const readSummary = `-- name: ReadSummary :many
SELECT 
  date, 
  operation, 
  COALESCE(source_name, '') as source_name, 
  COALESCE(event_name, '') as event_name, 
  value 
FROM itslog_summary
WHERE 
  source_name LIKE COALESCE(?, '%')
  AND
  operation LIKE ?
ORDER BY id
`

type ReadSummaryParams struct {
	SourceName sql.NullString
	Operation  string
}

type ReadSummaryRow struct {
	Date       string
	Operation  string
	SourceName string
	EventName  string
	Value      float64
}

func (q *Queries) ReadSummary(ctx context.Context, arg ReadSummaryParams) ([]ReadSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, readSummary, arg.SourceName, arg.Operation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadSummaryRow
	for rows.Next() {
		var i ReadSummaryRow
		if err := rows.Scan(
			&i.Date,
			&i.Operation,
			&i.SourceName,
			&i.EventName,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastRun = `-- name: UpdateLastRun :exec
;

UPDATE itslog_etl
  SET 
    last_run = CURRENT_TIMESTAMP 
WHERE 
  name = ?
`

func (q *Queries) UpdateLastRun(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, updateLastRun, name)
	return err
}

const updateLookup = `-- name: UpdateLookup :exec
INSERT OR IGNORE INTO itslog_lookup (
  timestamp, key_id, kind, hash, name
) VALUES (
  ?, ?, ?, ?, ?
)
`

type UpdateLookupParams struct {
	Timestamp time.Time
	KeyID     int64
	Kind      string
	Hash      int64
	Name      string
}

func (q *Queries) UpdateLookup(ctx context.Context, arg UpdateLookupParams) error {
	_, err := q.db.ExecContext(ctx, updateLookup,
		arg.Timestamp,
		arg.KeyID,
		arg.Kind,
		arg.Hash,
		arg.Name,
	)
	return err
}
