FROM golang:1.25.5-trixie

ENV VENV="/venv"
ENV PATH="$VENV/bin:$PATH"
RUN apt-get update ; apt-get install -y \
    python3 \
    python3-venv
RUN python3 -m venv $VENV
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt

CMD ["python3", "/app/containers/e2e/main.py"]