// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"time"
)

type ItslogDictionary struct {
	ID         int64
	KeyID      string
	Timestamp  time.Time
	SourceHash int64
	SourceName string
	EventName  string
	EventHash  int64
}

type ItslogEtl struct {
	ID       int64
	KeyID    string
	Inserted time.Time
	Name     string
	LastRun  sql.NullTime
	Sql      string
}

type ItslogEvent struct {
	ID          int64
	KeyID       string
	Timestamp   time.Time
	ClusterHash sql.NullInt64
	SourceHash  int64
	EventHash   int64
	ValueHash   sql.NullInt64
}

type ItslogLookup struct {
	ID        int64
	KeyID     string
	Timestamp time.Time
	Hash      int64
	Name      string
}

type ItslogMetadatum struct {
	ID        int64
	KeyID     string
	Timestamp time.Time
	Key       int64
	Value     string
}

type ItslogSummary struct {
	ID         int64
	KeyID      string
	Date       time.Time
	Operation  string
	SourceName sql.NullString
	EventName  sql.NullString
	Value      float64
}
